// Generated by Copilot

import * as vscode from "vscode";
import { TaskStatistics, ITaskStatisticsData } from "../models/task-statistics";
import { WorkspaceTaskManager } from "../models/task-manager";

export class StatisticsWebView {
  // Generated by Copilot
  private panel: vscode.WebviewPanel | undefined;
  constructor(
    private context: vscode.ExtensionContext,
    private taskManager: WorkspaceTaskManager
  ) {}

  public async show() {
    if (this.panel) {
      this.panel.reveal();
      return;
    }
    this.panel = vscode.window.createWebviewPanel(
      "vstasks.statistics",
      "Task Statistics",
      vscode.ViewColumn.One,
      {
        enableScripts: true,
        localResourceRoots: [this.context.extensionUri],
      }
    );
    const tasks = await this.taskManager.getAllTasks();
    const stats = TaskStatistics.calculate(tasks);
    this.panel.webview.html = this.getHtml(stats);
  }

  private getHtml(stats: ITaskStatisticsData): string {
    // Generated by Copilot
    const chartData = JSON.stringify({
      completed: stats.completed,
      pending: stats.pending,
      overdue: stats.overdue,
      byTag: stats.byTag,
      byDueDate: stats.byDueDate,
    });
    const scriptUri = this.panel?.webview.asWebviewUri(
      vscode.Uri.joinPath(this.context.extensionUri, "webview", "statistics.js")
    );
    const chartJsUri = "https://cdn.jsdelivr.net/npm/chart.js";
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Task Statistics</title>
  <script src="${chartJsUri}"></script>
  <link rel="stylesheet" href="${this.panel?.webview.asWebviewUri(
    vscode.Uri.joinPath(this.context.extensionUri, "webview", "styles.css")
  )}">
</head>
<body>
  <h1>Task Statistics</h1>
  <canvas id="taskChart" width="400" height="200"></canvas>
  <div id="byTag"></div>
  <div id="byDueDate"></div>
  <script>
    window.chartData = ${chartData};
  </script>
  <script src="${scriptUri}"></script>
</body>
</html>`;
  }
}
