// Generated by Copilot
import * as vscode from "vscode";
import { TaskDocumentHelper } from "./task-document-helper";

export class TaskHoverProvider implements vscode.HoverProvider {
  /**
   * Provide hover information for a task at the given position.
   */
  public provideHover(
    document: vscode.TextDocument,
    position: vscode.Position
  ): vscode.ProviderResult<vscode.Hover> {
    const task = TaskDocumentHelper.getTaskAtPosition(document, position);
    if (!task) {
      return undefined;
    }
    const lines: string[] = [];
    lines.push(`**Task**: ${task.description}`);
    lines.push(`**Status**: ${task.status}`);
    if (task.dueDate) {
      lines.push(`**Due**: ${task.dueDate.toLocaleDateString()}`);
    }
    if (task.priority !== undefined) {
      lines.push(`**Priority**: ${task.priority}`);
    }
    if (task.tags && task.tags.length > 0) {
      lines.push(`**Tags**: ${task.tags.join(", ")}`);
    }
    if (task.recurrence) {
      lines.push(`**Recurs**: ${task.recurrence.type}`);
    }
    return new vscode.Hover(lines.join("  \n"));
  }
}
